require 'rubygems'
Gem::manage_gems
require 'rake/gempackagetask'

spec = Gem::Specification.new do |s|
    s.platform  =   Gem::Platform::RUBY
    s.name      =   "netaddr"
    s.version   =   "1.5.0"
    s.author    =   "Dustin Spinhirne"
    s.summary   =   "A package for manipulating network addresses."
    s.files     =   FileList['lib/*.rb', 'test/*'].to_a
    s.require_path  =   "lib"
    s.test_files = Dir.glob('tests/*.rb')
    s.has_rdoc  =   true
    s.extra_rdoc_files  =   ["README", "Errors", "changelog"]
end 

Rake::GemPackageTask.new(spec) do |pkg|
    pkg.need_tar = true
end

task :test do
  require 'rake/runtest'
  Rake.run_tests('tests/*.rb')
end

task :default => "pkg/#{spec.name}-#{spec.version}.gem" do
   puts "generated latest version"
end 
